version: 2
jobs:
  build:
    working_directory: ~/CircleCI-App
    docker:
      -
        image: 'circleci/openjdk:8-jdk-stretch'
    steps:
      - checkout
      -
        restore_cache:
          key: 'CircleCI-App-{{ checksum "pom.xml" }}'
      -
        run: 'mvn dependency:go-offline'
      -
        save_cache:
          paths:
            - ~/.m2
          key: 'CircleCI-App-{{ checksum "pom.xml" }}'
      -
        run: 
          working_directory: ~/CircleCI-App
          command: ./gradlew dependencies
      -
        run:
          name: 'App upload and Set app id in environment variable.'
          command: "APP_UPLOAD_RESPONSE=$(curl -u \"nithyamani3:P4JKysg5WuchQxBfKQu1\" -X POST https://api-cloud.browserstack.com/app-automate/upload -F \"file=@/Users/nithyamani/Desktop/APPS/WikipediaSample.apk\")\nAPP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r \".app_url\")\nif [ $APP_ID != null ]; then\n  echo \"Apk uploaded to BrowserStack with app id : \",$APP_ID;\n  echo \"export BROWSERSTACK_APP_ID=$APP_ID\" >> $BASH_ENV;\n  source $BASH_ENV;\n  echo \"Setting value of BROWSERSTACK_APP_ID in environment variables to  \",$APP_ID;\nelse\n  UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r \".error\")\n  echo \"App upload failed, reason : \",$UPLOAD_ERROR_MESSAGE\n  exit 1;\nfi\n"
      -
        run: mvn test -P single
      -
        store_test_results:
          path: target/surefire-reports
      -
        store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
