version: 2
jobs:
  build:
    working_directory: ~/CircleCI-App
    docker:
      -
        image: 'circleci/openjdk:8-jdk-stretch'
    steps:
      - checkout
      -
        restore_cache:
          key: 'CircleCI-App-{{ checksum "pom.xml" }}'
      -
        run: 'mvn dependency:go-offline'
      -
        save_cache:
          paths:
            - ~/.m2
          key: 'CircleCI-App-{{ checksum "pom.xml" }}'
      -
        run: 
          ./gradlew assembleDebug
      -
        run:
          name : App upload and Set app id in environment variable.
          command : |
          APP_UPLOAD_RESPONSE=$(curl -u "nithyamani3:P4JKysg5WuchQxBfKQu1" -X POST https://api-cloud.browserstack.com/app-automate/upload -F "file=@/Users/nithyamani/Desktop/APPS/WikipediaSample.apk")
          APP_ID=$(echo $APP_UPLOAD_RESPONSE | jq -r ".app_url")
          if [ $APP_ID != null ]; then
            echo "Apk uploaded to BrowserStack with app id : ",$APP_ID;
            echo "export BROWSERSTACK_APP_ID=$APP_ID" >> $BASH_ENV;
            source $BASH_ENV;
            echo "Setting value of BROWSERSTACK_APP_ID in environment variables to  ",$APP_ID;
          else
            UPLOAD_ERROR_MESSAGE=$(echo $APP_UPLOAD_RESPONSE | jq -r ".error")
            echo "App upload failed, reason : ",$UPLOAD_ERROR_MESSAGE
            exit 1;
          fi
      - 
        run: 
          ./gradlew test
      -
        store_test_results:
          path: target/surefire-reports
      -
        store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
